spring.application.name=Security


spring.security.oauth2.client.registration.google.client-id=1041467637743-tlfqjrdp7kkf11vcqe34le6021fq54e3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email,https://www.googleapis.com/auth/contacts.readonly
#spring.security.oauth2.client.registration.google.scope=https://www.googleapis.com/auth/userinfo.profile,https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/contacts.readonly
logging.level.org.springframework.security=TRACE